In [ ]:
#Задание 1
"""
Для датафрейма log из материалов занятия создайте столбец source_type по следующим правилам:

если источник traffic_source равен yandex или google, то в source_type ставится organic
для источников paid и email из России - ставим ad
для источников paid и email не из России - ставим other
все остальные варианты берем из traffic_source без изменений

"""

In [1]:
import pandas as pd

In [16]:
log = pd.read_csv("visit_log.csv", sep = ";")

In [15]:
def source_type_func(new_list):
    if new_list["traffic_source"] == "yandex":
        return "organic"
    if new_list["traffic_source"] == "google":
        return "organic"
    if new_list["traffic_source"] == "paid" and new_list["region"] == "Russia":
        return "ad"
    if new_list["traffic_source"] =="email" and new_list["region"] =="Russia":
        return "ad"
    if new_list["traffic_source"] =="email" or new_list["traffic_source"] =="paid" and new_list["region"] != "Russia":
        return "Other"
    
    return new_list["traffic_source"]

In [16]:
log["source_type"] = log.apply(source_type_func, axis = 1)
log.head(40)

,timestamp,visit_id,url,region,user_id,traffic_source,source_type
0,1549980692,e3b0c44298,https://host.ru/3c19b4ef7371864fa3,Russia,b1613cc09f,yandex,organic
1,1549980704,6e340b9cff,https://host.ru/c8d9213a31839f9a3a,Russia,4c3ec14bee,direct,direct
2,1549980715,96a296d224,https://host.ru/b8b58337d272ee7b15,Russia,a8c40697fb,yandex,organic
3,1549980725,709e80c884,https://host.ru/b8b58337d272ee7b15,Russia,521ac1d6a0,yandex,organic
4,1549980736,df3f619804,https://host.ru/b8b58337d272ee7b15,Russia,d7323c571c,yandex,organic
5,1549980742,8855508aad,https://host.ru/df646c3676cc259fa0,Russia,fc43898e47,yandex,organic
6,1549980742,b0f66adc83,https://host.ru/b8b58337d272ee7b15,Russia,13fc55e781,paid,ad
7,1549980754,837885c8f8,https://host.ru/108ce4b365afb7b88e,Russia,cb5082b6f6,direct,direct
8,1549980760,af5570f5a1,https://host.ru/3004a8273caeef2867,China,45664f7af2,direct,direct
9,1549980765,3e7077fd2f,https://host.ru/df646c3676cc259fa0,Russia,6f9de8c8b6,email,ad
10,1549980777,01d448afd9,https://host.ru/a5dda93e70318570c0,India,27e76a4a80,direct,direct
11,1549980785,71b6c1d538,https://host.ru/c8d9213a31839f9a3a,Ukraine,3b13701488,google,organic
12,1549980789,15ec7bf0b5,https://host.ru/8e88d4703848cc0ec4,Russia,6d1d81f7f8,paid,ad
13,1549980792,dd46c3eebb,https://host.ru/3004a8273caeef2867,China,7e301c8c41,direct,direct
14,1549980793,e7ecebbc59,https://host.ru/05e41944dd85a900a6,Belarus,ac52dedc3b,direct,direct
15,1549980797,5322fecfc9,https://host.ru/4adc8a29b212051b04,Belarus,9a45d98867,paid,Other
16,1549980801,374708fff7,https://host.ru/39fa884393666d45fc,Russia,e9bd59e22d,google,organic
17,1549980807,0a88111852,https://host.ru/2fcb223266880ccf57,Ukraine,a2ba8fa3db,paid,Other
18,1549980814,60daa3a5f7,https://host.ru/ef57543002ce2a0f2a,Belarus,72cb10fb5c,direct,direct
19,1549980816,d6fd62f5ce,https://host.ru/f1eb4601740d627ab0,Belarus,7269dcd869,direct,direct
20,1549980816,de47c9b27e,https://host.ru/8fe7c39e5c598bbc54,Ukraine,2f25b6e26a,email,Other
21,1549980823,c90232586b,https://host.ru/da83c74e35e7806fe0,Ukraine,a00405d70c,google,organic
22,1549980827,6a4875ddac,https://host.ru/f2297425e1328e9e35,Ukraine,ea1bf97284,yandex,organic
23,1549980839,015275e61f,https://host.ru/c8d9213a31839f9a3a,Russia,21bdc57777,email,ad
24,1549980842,9d908ecfb6,https://host.ru/ae8a036d7f44d0bcd9,China,583b1a1636,direct,direct
25,1549980844,61126de1b7,https://host.ru/060d9bdbcba66b8bb3,Russia,9de3f97d4f,direct,direct
26,1549980852,659d36ca56,https://host.ru/4adc8a29b212051b04,Russia,c4bd1ae3af,paid,ad
27,1549980853,ea49aa9f6f,https://host.ru/1afc5618562365020a,Russia,20e8e91ecf,email,ad
28,1549980862,3addfb141c,https://host.ru/186c4d6b47dbde0e74,Russia,3f64fc1a87,yandex,organic
29,1549980874,11e431c215,https://host.ru/05e41944dd85a900a6,Russia,a15f66b89b,paid,ad
30,1549980877,0679246d6c,https://host.ru/da83c74e35e7806fe0,Ukraine,f8043c57c9,direct,direct
31,1549980881,fd08be957b,https://host.ru/8fe7c39e5c598bbc54,Ukraine,8779289616,direct,direct
32,1549980886,66687aadf8,https://host.ru/1afc5618562365020a,Ukraine,45c62a0196,direct,direct
33,1549980897,7f9c9e31ac,https://host.ru/ac2d98a5a63e7c6e28,Belarus,38f45e7f9b,email,Other
34,1549980903,eb142b0cae,https://host.ru/6fda01ec57f23abc9e,Russia,ffbb3278c4,yandex,organic
35,1549980908,0d5535e13c,https://host.ru/8880fd00cf23066541,Russia,51baf057bb,email,ad
36,1549980918,6db65fd59f,https://host.ru/39fa884393666d45fc,Belarus,3739124008,direct,direct
37,1549980930,ab24a95f44,https://host.ru/1be58f19f26458f2fe,Russia,f880b1e734,direct,direct
38,1549980931,762b023699,https://host.ru/8880fd00cf23066541,Belarus,00fad95415,yandex,organic
39,1549980932,94c11ed3c3,https://host.ru/da83c74e35e7806fe0,Russia,1875754379,yandex,organic

In [ ]:
#Задание 2
"""
В файле URLs.txt содержатся url страниц новостного сайта. 
Вам необходимо отфильтровать его по адресам страниц с текстами новостей. 
Известно, что шаблон страницы новостей имеет внутри url следующую конструкцию: /, затем 8 цифр, затем дефис. 
Выполните следующие действия:

Прочитайте содержимое файла с датафрейм
Отфильтруйте страницы с текстом новостей, используя метод str.contains и регулярное выражение в соответствии 
с заданным шаблоном

"""

In [9]:
df = pd.read_csv("URLs.txt")
df["adress"] = df["url"].str.contains(r'(?<=/)\d+-')
filter_true = df.loc[df.adress == True]
filter_true.head()

                                                 url  adress
3  /politics/36188461-s-marta-zhizn-rossiyan-susc...    True
4  /world/36007585-tramp-pridumal-kak-reshit-ukra...    True
5  /science/36157853-nasa-sobiraet-ekstrennuyu-pr...    True
6  /video/36001498-poyavilis-pervye-podrobnosti-g...    True
7  /world/36007585-tramp-pridumal-kak-reshit-ukra...    True

In [ ]:
#Задание 3
"""
Используйте файл с оценками фильмов ml-latest-small/ratings.csv. 
Посчитайте среднее время жизни пользователей, которые выставили более 100 оценок. 
Под временем жизни понимается разница между максимальным и минимальным значением столбца timestamp 
для данного значения userId.
"""

In [1]:
import pandas as pd

In [2]:
# Сделаем таблицу ключ с нужными ID (более 100 оценок)
data = pd.read_csv("доп материалы/ml-latest-small/ratings.csv")
data_count = data.drop(["movieId","timestamp"],axis =1).groupby("userId").count().rename(columns={"rating":"count"})
data_count = data_count.loc[data_count["count"] > 100]
data_count.head()

        count
userId
4         204
8         116
15       1700
17        363
19        423

In [19]:
# Делаем join макс время и отсавляем только те ID, где больше 100 оценок.
for_max_data = data_count.join(max_data_pivot, how = "inner").drop(["count"], axis=1)
for_max_data.head()

               max
userId
4        949982274
8       1154474527
15      1469330735
17      1127476640
19       855195373

In [20]:
# Делаем join мин время и отсавляем только те ID, где больше 100 оценок.
for_min_data = data_count.join(min_data_pivot, how = "inner").drop(["count"], axis=1)
for_min_data.head()

               min
userId
4        949778714
8       1154389340
15       997937239
17      1127468587
19       855190091

In [21]:
# объединим мин и макс даты в один датафрейм и находим разницу
final_data = for_min_data.join(for_max_data, how = "left")
final_data["Average_time"] = final_data["max"] - final_data["min"] 
final_data.head()

               min         max  Average_time
userId
4        949778714   949982274        203560
8       1154389340  1154474527         85187
15       997937239  1469330735     471393496
17      1127468587  1127476640          8053
19       855190091   855195373          5282

In [5]:
#Находим максимлаьное время для каждого ID
max_data_pivot = data.pivot_table(
    index = "userId",
    values='timestamp',
    aggfunc = "max",
    fill_value = 0).rename(columns={"timestamp":"max"})
max_data_pivot.head(8)

               max
userId
1       1260759205
2        835356246
3       1298932787
4        949982274
5       1163375145
6       1109258285
7        851869291
8       1154474527

In [3]:
#Находим минимальное  время для каждого ID
min_data_pivot = data.pivot_table(
    index = "userId",
    values='timestamp',
    aggfunc = "min",
    fill_value = 0).rename(columns={"timestamp":"min"})
min_data_pivot.head(8)

               min
userId
1       1260759108
2        835355395
3       1298861589
4        949778714
5       1163373044
6       1108134263
7        851866703
8       1154389340

In [ ]:
#Задание 4
"""
Дана статистика услуг перевозок клиентов компании по типам (см. файл с кодом занятия).
Необходимо сформировать две таблицы:
таблицу с тремя типами выручки для каждого client_id без указания адреса клиента
аналогичную таблицу по типам выручки с указанием адреса клиента
Обратите внимание, что в процессе объединения таблиц данные не должны теряться.

In [23]:
import pandas as pd